### ISSUE TITLE
Looping feature request

### ISSUE THREAD

**Issue by Adrian-Nelson** [adrianstevens/Xamarin-Plugins#1]
Hi, This is a really nice Xamarin cross-platform sound library!

I am using it to provide sound effects for my Xamarin.Forms / Skia word game.

I've also been trying to use it to play some background music which loops, however, using the PlaybackEnded event to play the music again isn't seemless and there is a slight delay.

Any chance you could implement the option to loop the sound? (possibly as an optional parameter to the existing Play() method or as a new PlayLooped() method)

Many thanks for the current library and thanks in advance for any looping support!

Best regards,
Adrian Nelson

**Comment by adrianstevens** [comment]
Hi Adrian - I'm really glad you're finding it useful! (love SkiaSharp btw)

And absolutely, I should be able to get that done this weekend (if not sooner).

**Comment by Adrian-Nelson** [comment]
Fantastic - thanks very much for the quick response.

**Comment by adrianstevens** [comment]
No problem at all - give this version a try: https://www.nuget.org/packages/Xam.Plugin.SimpleAudioPlayer/0.8.1-beta 

I've added a public Loop property.

When I was testing, iOS and Android worked exactly as expected. UWP was dropping out randomly. I'll explore that further this week.

**Comment by Adrian-Nelson** [comment]
Many thanks for doing this, I just tried it out on iOS - perfect!

What more can I say!

Best regards,
Adrian Nelson

**Comment by adrianstevens** [comment]
Excellent! I'm closing this issue - feel free to open another if you have any other requests/suggestions
