### ISSUE TITLE
Crashes on most Android devices

### ISSUE THREAD

**Issue by ivanicin** [adrianstevens/Xamarin-Plugins#11]
This is working properly on iOS, UWP on Android on emulator and some devices. But on most popular Android devices (like Samsung, LG) it crashes. And on those that work it frequently plays the sound multiple times.

**Comment by adrianstevens** [comment]
Can you provide the make, model and OS version of the devices you're having issues with?

**Comment by ivanicin** [comment]
I've got incorrect reports from users that made me believe that this was causing the crashes.

**Comment by adrianstevens** [comment]
Thank you Ivanicin for taking the time to report back and close the issue
