### ISSUE TITLE
SimpleAudioPlayer (IOS): Loop = false makes sound loop twice.

### ISSUE THREAD

**Issue by jorgen-k** [adrianstevens/Xamarin-Plugins#12]
If you set the property Loop to false in IOS the sound will loop twice.

Expected behaviour is that the sound should not loop.

Fault is in SimpleAudioPlayer.IOS/SimpleAudioPlayerImplementation.cs line 68

`player.NumberOfLoops = _loop ? -1 : 1;`

Should be:

`player.NumberOfLoops = _loop ? -1 : 0;`

Reference: https://developer.apple.com/documentation/avfoundation/avaudioplayer/1386071-numberofloops

**Comment by adrianstevens** [comment]
Thank you @jorgen-k! - I'll get this fixed in the next release
