### ISSUE TITLE
Loop doesn't work at all on Android

### ISSUE THREAD

**Issue by superbluecool** [adrianstevens/Xamarin-Plugins#13]
set the player.Loop to true, but it tries to play for second time for couple of seconds, then it stops.

Even the samples don't loop on Android, tried the latest version. Help!

Does it work for anybody else?

**Comment by adrianstevens** [comment]
I am testing on a Google Pixel 2 running Android 8.1.

Let me know what device/emulator you're using and I'll see if I can reproduce the issue.

Cheers!

**Comment by adrianstevens** [comment]
This _may_ be fixed in the latest version (1.0.2).

**Comment by adrianstevens** [comment]
this should be fixed in the latest stable release - closing issue
