### ISSUE TITLE
Sound loops twice on Android 6.0.1

### ISSUE THREAD

**Issue by Charly01** [adrianstevens/Xamarin-Plugins#15]
On Android 5.0 Play() did work fine.
With Android 6.0.1 sometimes(!) - mainly after having played the same sound two or three times - Play() playes twice!

**Comment by adrianstevens** [comment]
I'll do some testing on the Android 6.0 emulator. I don't currently have a physical device running Android 6 unfortuantely.

**Comment by adrianstevens** [comment]
I've been able to re-produce this issue on a Moto G (2nd gen) running Android 6.0. Hopefully I'll be able to fix the issue and release an update ASAP.

It's working as expected on my Android 5.x and 8.x devices.

**Comment by Charly01** [comment]
Great!
😊

Gesendet von meinem Windows 10 Phone

Von: Adrian Stevens<mailto:notifications@github.com>
Gesendet: Freitag, 26. Januar 2018 18:18
An: adrianstevens/Xamarin-Plugins<mailto:Xamarin-Plugins@noreply.github.com>
Cc: Charly Spitzenberger<mailto:carl.spitzenberger@newcomer.de>; Author<mailto:author@noreply.github.com>
Betreff: Re: [adrianstevens/Xamarin-Plugins] Sound loops twice on Android 6.0.1 (#15)


I've been able to re-produce this issue on a Moto G (2nd gen) running Android 6.0. Hopefully I'll be able to fix the issue and release an update ASAP.

It's working as expected on my Android 5.x and 8.x devices.

**Comment by adrianstevens** [comment]
Looks like I've found the issue. For stability on older versions on Android I was forcing the seek position back to 0 and calling Perpare() after playback had ended. 

On Android 6, calling Prepare() is restarting the audio in some cases which looks like a bug. However, if you look at the MediaPlayer state diagram, we shouldn't need to seek or prepare at all after playback completes.

For the next release of SimpleAudioPlayer I'll let the Android MediaPlayer take care of the MediaPlayer state after playback completes for Android 6.0 and up. In testing it's been working perfectly on newer devices.

**Comment by adrianstevens** [comment]
I've just released SimpleAudioPlayer 1.0.2 which should fix the problem. I'm closing the issue but please re-open if see any related problems.
