### ISSUE TITLE
Stop = Replay the first few milliseconds before stopping

### ISSUE THREAD

**Issue by bodeg** [adrianstevens/Xamarin-Plugins#16]
Hi
In Android ( Android 6.0 - API 23)

AudioPlayer?.Stop();

After calling Stop - the player seek to beginning (0), play the first few milliseconds, and then stops.

Thanks.

**Comment by adrianstevens** [comment]
Hi bodeg - are you seeing this on a simulator or a physical device? And if it's a device, can you provide the make and model?

**Comment by bodeg** [comment]
Hi Adrian
You are right - it is seeing on the emulator.  
On real device it works perfectly.

Thanks. alon.

**Comment by adrianstevens** [comment]
Very glad to hear - and thanks!

**Comment by olegpidsadnyi** [comment]
@adrianstevens We have a real device on Android 6 that reproduces this issue. It's a Zebra TC56 (Symbol or Motorola).
