### ISSUE TITLE
Xamarin Forms - Play Audio in Background Mode not working

### ISSUE THREAD

**Issue by Sun3** [adrianstevens/Xamarin-Plugins#18]
Is there a way to play audio in Background Mode in Xamarin Forms using .NET 2.0 Standard. I am currently testing on an iPhone Device and once you tap the Home Button and app closes so does the audio.

Below is code in the Xamarin Forms .NET 2.0 Standard project:
```
void PlayAudioOne()
{
            var assembly = typeof(App).GetTypeInfo().Assembly;
            Stream audioStream = assembly.GetManifestResourceStream("Xam1." + "Sounds.Coldplay-One.mp3");
            
            var player = Plugin.SimpleAudioPlayer.CrossSimpleAudioPlayer.Current;
            player.Load(audioStream);
            player.Play();
}
```

Thank you.

**Comment by pakbaz** [comment]
I have the same issue

**Comment by adrianstevens** [comment]
For iOS you'll need to declare the background audio capability otherwise iOS shutdown your app when minimized.

There's some coverage in Xamarin University  in IOS211 (university.xamarin.com). You can take a look at the code for free here: https://github.com/xamarinuniversity/IOS211

This is probably beyond the use-case of SimpleAudioPlayer but I'd be happy to investigate further if there's demand.

**Comment by gharwood1** [comment]
@adrianstevens 
Does #8 not apply here? If so it might be good to add something about how to get audio playing in the background of both IOS and Android in the README. I definitely think background audio should be a feature. So many audio only apps require it. (audible, spotify, etc)

Thoughts?

**Comment by dalinarkholin** [comment]
@adrianstevens
Does #8 not apply here? If so it might be good to add something about how to get audio playing in the background of both IOS and Android in the README. I definitely think background audio should be a feature. So many audio only apps require it. (audible, spotify, etc)

Thoughts?

**Comment by traceyhemp12** [comment]
@adrianstevens 
Have you looked further into adding the backgrounding to Simple Audio Player?

**Comment by sachinkanadia** [comment]
@adrianstevens 
I am having the same issue, I need the background audio to play when the iOS app is backgrounded. I'd be very appreciative if this can be looked into. Things I have tried:
1) Updated to the latest version of Simple Audio Player.
2) Enabled background audio within info.plist.
However still no joy. Please help. Many Thanks

**Comment by sachinkanadia** [comment]
For anyone who is interested - I managed to resolve the issue on iOS background audio.
I added the following call to the FinishedLaunching method of the AppDelegate class. Seems to be working fine now. Remember to Enable background audio within info.plist!

        private void EnableBackgroundAudio()
        {
            var currentSession = AVAudioSession.SharedInstance();
            currentSession.SetCategory(AVAudioSessionCategory.Playback,
AVAudioSessionCategoryOptions.MixWithOthers);
            currentSession.SetActive(true);
        }

**Comment by adrianstevens** [comment]
Thanks @sachinkanadia - I'll add this to the readme!

Closing issue

**Comment by sabrigo** [comment]
thank you @sachinkanadia
