### ISSUE TITLE
Sound plays on Android, not on iOS

### ISSUE THREAD

**Issue by BioTurboNick** [adrianstevens/Xamarin-Plugins#19]
I don't fully know if this plugin is at fault, but I'm looking into it. I have a sound that plays on Android but not on iOS. As far as I can tell, the file is found and loaded (the player has the correct duration)

The sound file (m4a) in question is extremely short in duration, less than 100 ms, and has a ~10 ms leading silence. Padding the sound on both sides by lengthy silence allows it to play.

I'm investigating lengthening this sound file or having a leading silence and will amend.

**Comment by BioTurboNick** [comment]
Update: I took one of my sounds that was working and removed any leading silence. It was audible but the volume was quite low. Seems that there is a fading increase in volume at the start of playback?

**Comment by campersau** [comment]
We had a similar issue and fixed it by setting the following in the `AppDelegate`:
```csharp
AVAudioSession.SharedInstance().SetCategory(AVAudioSessionCategory.Playback, AVAudioSessionCategoryOptions.DefaultToSpeaker);
```

**Comment by BioTurboNick** [comment]
@campersau - Your fix is similar to what I posted in #22, though I didn't realize we could set that manually. I'll check if it solves this specific issue too.

**Comment by adrianstevens** [comment]
Yes you can set the AVAudioSession external to the plugin (which is really convenient with iOS).

Currently SimpleAudioPlayer isn't making any changes to the session. 

I'll leave this issue open for further discussion.

**Comment by adrianstevens** [comment]
Closing issue
