### ISSUE TITLE
Android: MediaPlayer finalized without being released

### ISSUE THREAD

**Issue by tsldevteam** [adrianstevens/Xamarin-Plugins#2]
On Android (v6.0.1 - Moto G3) there is a repeated warning when the same player is used to load and play sounds which occurs after ~ 15 sounds have been played.
`05-16 15:38:11.554 W/MediaPlayer-JNI(23216): MediaPlayer finalized without being released
`
Perhaps the .Release() method should be called before the `player` instance is Disposed() ?

**Comment by adrianstevens** [comment]
@tsldevteam I think you're absolutely right and the MediaPlayer documentation seems to confirm. I've made the fix and you'll see it in the next release.

**Comment by adrianstevens** [comment]
this is fixed in v0.9.0 - closing
