### ISSUE TITLE
Broken Balance setting logic

### ISSUE THREAD

**Issue by lion92pl** [adrianstevens/Xamarin-Plugins#20]
In [SimpleAudioPlayer iOS implementation line 182](https://github.com/adrianstevens/Xamarin-Plugins/blob/master/SimpleAudioPlayer/SimpleAudioPlayer/Plugin.SimpleAudioPlayer.iOS/SimpleAudioPlayerImplementation.cs#L182) should be `-1`. Same in Android and maybe more.

**Comment by adrianstevens** [comment]
I'll get that fixed ASAP
