### ISSUE TITLE
PlaybackEnded triggering multiple times

### ISSUE THREAD

**Issue by stevenchingch** [adrianstevens/Xamarin-Plugins#21]
First, thank you for this amazing Plugin for Xamarin Forms. 

Been running into an issue that is getting the PlaybackEnded event triggered multiple times on Android. I do not have an iOS device currently, so I cannot confirm for the iOS side of things.
My use case is as below.

1) Load an audio file from the Environment SpecialFolder into a Stream
2) Load the stream into the AudioPlayer
3) Start playback
When the PlaybackEnded event is triggered
4) Load another audio file into Stream
5) Load the stream into the AudioPlayer
6) Start playback

By doing this again and again, I'm getting multiple event triggers to the PlaybackEnded event. (eg. I only playback 2 files and should only get two PlaybackEnded triggers but I'm getting 6 triggers instead)

EDIT:
Looking at the source code, is it possible that the event handler OnPlaybackEnded is getting added to the player's Completed event multiple times for the same player?

Also, if anyone can suggest any enhancement to my logic, I would be extremely appreciative. Thank you.
Currently, I'm loading the file from a Stream that is in my Environment.SpecialFolder.Personal directory using the ReadAllBytes method. I understand that it is not memory efficient ?!? Is there any other way around this? (Even though I'm just loading short and small audio files)

Thank you! and have a great day

**Comment by stevenchingch** [comment]
Found the problem. At Android line 93, there should be
player.Completion -= OnPlaybackEnded 

before the 

player.Reset();

**Comment by adrianstevens** [comment]
Thanks @stevenchingch - I'll get this fixed in the next release (aiming for this weekend)

**Comment by adrianstevens** [comment]
I believe this is fixed with the latest commits - I'll test carefully before the next release

**Comment by adrianstevens** [comment]
this is now fixed - closing issue
