### ISSUE TITLE
Add WPF version of SimpleAudioPlayer to repository

### ISSUE THREAD

**Issue by anders9ustafsson** [adrianstevens/Xamarin-Plugins#23]
With the previously released preview of *Xamarin Forms* for [WPF](https://www.nuget.org/packages/Xamarin.Forms.Platform.WPF), it has become even more interesting to also provide a WPF implementation of *Simple Audio Player*.

I have made a very simplistic attempt to provide a WPF specific implementation in [my fork](https://github.com/anders9ustafsson/Xamarin-Plugins/commit/c8148047d32fda9925c0520f7f5e70cbaa1185fb) of this repository. Please feel free to base a more reliable implementation on this effort.

**Comment by anders9ustafsson** [comment]
Great!

I should point out that I am a complete novice when it comes to the WPF MediaPlayer class, and the Load(string) method is not tested either. So before releasing anything based on this code, please take a thorough look to see if/how things could be made better.

**Comment by anders9ustafsson** [comment]
One thing I do not take care of very well for example is the temporary output of the audio stream to file. I am not checking that I have authorization to dump it, and I am also not cleaning it up after it has been loaded. I primarily needed a "quick-and-dirty" solution, which I think my code reflects very well :-)

**Comment by adrianstevens** [comment]
That's perfect - getting it working is the hard part! I have a couple of colleagues I lean-on for code reviews; I'll run it by them before I publish.

**Comment by anders9ustafsson** [comment]
Thanks! I will make a pull request to make it easier for you to incorporate and modify the code. 

Best regards,
Anders

**Comment by adrianstevens** [comment]
Fantastic! I'll get it merged this weekend - the code looks great

**Comment by adrianstevens** [comment]
thanks again @anders9ustafsson - PR is merged - I'll push an update out with the WPF package in the next few days

**Comment by adrianstevens** [comment]
This has been added and published in v1.2.0 beta 

I need to do some additional testing on the WPF and Tizen implementations and then I'll move it to stable

**Comment by adrianstevens** [comment]
this has been published - closing issue
