### ISSUE TITLE
When changing a namespace, keep stubs with [Obselete] to notify user.

### ISSUE THREAD

**Issue by BioTurboNick** [adrianstevens/Xamarin-Plugins#27]
My experience:

1. Upgraded to 1.1.0
2. Builds failed, saying it could not find the Abstractions namespace.
3. I assume it must be a linker issue, tried downgrading, enable/disable linker options and ProGuard.
4. Intellisense still insists that Abstractions exists and that ISimpleAudioPlayer is in it.
5. The Dependency list shows a caution icon on SimpleAudioPlayer, but no indication of why.
6. I come here to figure out what changed, see you removed a namespace.
7. Builds fine after removing Abstractions namespace.
8. Restarting Visual Studio caused Intellisense to figure it out.

All that said--the transition would be much easier if there was a notice of the change.

**Comment by adrianstevens** [comment]
thx @BioTurboNick I really appreciate the tip and sorry about the headache

I hate changing the API after it's published but that abstract namespace added zero value 

I'll update with [Obsolete] for the next version - it might help a few ppl that haven't updated yet
