### ISSUE TITLE
Not working properly on UWP

### ISSUE THREAD

**Issue by leisn** [adrianstevens/Xamarin-Plugins#30]
When stop the player and restart, it start at old postion ,seems Seek(0) is no use.

And I found when execute to 
`player.Source = MediaSource.CreateFromStream(stream.AsRandomAccessStream(), string.Empty);`
always throw  _"**System.NotSupportedException**"_ 
Change **string.Empty** to **"audio/x-wav"** is useless.

**Comment by adrianstevens** [comment]
This should be fixed in the latest version -closing issue
