### ISSUE TITLE
How do I stop the unrelenting messages in output?

### ISSUE THREAD

**Issue by primehalo** [adrianstevens/Xamarin-Plugins#32]
Once I start playing a tone I see a bunch of MediaPlayer messages in the output window. Even after I stop playback I keep getting these messages over and over:

> 07-11 23:01:51.721 V/MediaPlayer(19926): getDuration_l
> 07-11 23:01:51.721 V/MediaPlayer-JNI(19926): getDuration: 21312 (msec)
> 07-11 23:01:51.721 V/MediaPlayer-JNI(19926): getCurrentPosition: 0 (msec)
> 07-11 23:01:51.721 V/MediaPlayer(19926): getDuration_l
> 07-11 23:01:51.721 V/MediaPlayer-JNI(19926): getDuration: 21312 (msec)
> 07-11 23:01:51.781 V/MediaPlayer-JNI(19926): isPlaying: 0

These constant streaming messages make it very difficult to view other output that I'm looking for. Is there any way to make them stop?

**Comment by adrianstevens** [comment]
These messages are unfortunately come from the Android Java SDK and there isn't currently a way to disable it. This issue isn't unique to this plugin.

There's a good discussion here: https://forums.xamarin.com/discussion/86321/restrict-debug-messages-in-the-output-window-to-just-my-debug-messages

closing issue
