### ISSUE TITLE
Load(Stream audioStream) error on iOS Could not initialize an instance of the type...

### ISSUE THREAD

**Issue by nexxuno** [adrianstevens/Xamarin-Plugins#34]
Hello,
I'm having this problem on iOS when trying to play an mp3 file.
This is how I use the library:
  ` await soundsPlayer.PlaySoundAsync("BeltMap.Sounds.Beep1.mp3");`
```
public async Task PlaySoundAsync(string file)
        {
            try
            {
                AcquireIOSPlaybackChannel();
                audioPlayer.Load(GetStreamFromFile(file));
                audioPlayer.Play();
            }
            catch(Exception ex)
            {
                Dictionary<string, string> dic = new Dictionary<string, string>();
                dic.Add("Error during PlaySoundAsync", "Could be a file not found?");
                typeof(App).GetTypeInfo().Assembly.GetManifestResourceNames().ToList().ForEach(x => dic.Add(Guid.NewGuid().ToString(), x));
                Crashes.TrackError(ex, dic);
                throw;
            }
        }

        private Stream GetStreamFromFile(string filename)
        {
            var assembly = typeof(App).GetTypeInfo().Assembly;
            var stream = assembly.GetManifestResourceStream(filename);

            if(stream == null)
            {
                Crashes.TrackError(new NullReferenceException($"Stream created for file {filename} is null. More info: {assembly.GetManifestResourceInfo(filename).FileName} {assembly.GetManifestResourceInfo(filename).ResourceLocation.ToString()}"));
            }

            return stream;
        }

```
The files are in the resources because with a call to typeof(App).GetTypeInfo().Assembly.GetManifestResourceNames()
I get both BeltMap.Sounds.Beep1.mp3 BeltMap.Sounds.Beep2.mp3

Moreover the same code works on Android.

This is the full error:
Could not initialize an instance of the type 'AVFoundation.AVAudioPlayer': the native 'initWithData:error:' method returned nil. It is possible to ignore this condition by setting ObjCRuntime.Class.ThrowOnInitFailure to false.

And stacktrace:
Foundation
NSObject.InitializeHandle (System.IntPtr handle, System.String initSelector)
AVFoundation.AVAudioPlayer
AVFoundation.AVAudioPlayer..ctor (Foundation.NSData data, System.IntPtr outError) <0x100e64054 + 0x00063> in <0a1f753a89814f48b3664aa368375dde#7123272e43ddfa26c5a56b134a02f5dd>:0
AVFoundation
AVAudioPlayer.FromData (Foundation.NSData data)
Plugin.SimpleAudioPlayer
SimpleAudioPlayerImplementation.Load (System.IO.Stream audioStream)
BeltMap.Services
SoundsPlayer+<PlaySoundAsync>d__5.MoveNext ()

iOS 11.4.1

**Comment by adrianstevens** [comment]
It's possible iOS has an issue with the files themselves - have you tried with any other files?

**Comment by nexxuno** [comment]
I'll try as soon as I can and let you know, thanks.
________________________________

**Comment by nexxuno** [comment]
I tried with some wav files and it works so ffor me this can be closed, you can evaluate the feasability of a better error message. Thanks, Paolo
