### ISSUE TITLE
Load(stream) android bad file handling - used memory grows

### ISSUE THREAD

**Issue by nexxuno** [adrianstevens/Xamarin-Plugins#35]
Each time the method is called a file copy is created but when the object SimplePlayer object is disposed only the last loaded file is removed from the cache. 

This makes used memory grow forever.

**Comment by adrianstevens** [comment]
You're absolutely right - I'll get that fixed in the next release 

thank you!

**Comment by adrianstevens** [comment]
this is now fixed - closing issue

**Comment by nexxuno** [comment]
Ok thanks!
________________________________
