### ISSUE TITLE
Not working on macOS

### ISSUE THREAD

**Issue by aquisio** [adrianstevens/Xamarin-Plugins#37]
I have a cross-platform application that targets iOS, Android, WIndows and Mac.

Sound works correctly on iOS, Android and Windows, but throws on macOS when attempting to access CrossSimpleAudioPlayer.Current:

"This functionality is not implemented in the .NET standard version of this assembly. Reference the NuGet package from your platform-specific (head) application project in order to reference the platform-specific implementation."

I confirm that the SimpleAudioPlayer Nuget package is reference in the macOS head project.

**Comment by adrianstevens** [comment]
Interesting, I have tested macOS in the past and it was working correcly. I've just updated the sample project and released v1.3.0. Definitely let me know if you're still seeing issues.

**Comment by Heavymaskinen** [comment]
Hi
I have the same problem. There seems to be no implementation-class in the folder Plugin.SimpleAudioPlayer.macOS - maybe that's the problem?

**Comment by adrianstevens** [comment]
I'll be releasing v1.3.1 this week - I'll verify macOS is working correctly before publishing

Cheers!

**Comment by adrianstevens** [comment]
Thank you for taking the time to report the issue - 1.3.1 has been tested and is working on macOS - closing issue
