### ISSUE TITLE
Balance Doesn't Work

### ISSUE THREAD

**Issue by robbpriestley** [adrianstevens/Xamarin-Plugins#40]
I can't seem to get balance to work.

Assigning it doubles in the range -1 to 1.

I have verified volume is working.

Is it possibly because balance only works with monophonic sounds and I am using all stereo sounds?

Tested with the iOS implementation.

**Comment by robbpriestley** [comment]
I forked the code and I've just spent the evening exploring the balance situation.

----
**Bug #1**
/Xamarin-Plugins/SimpleAudioPlayer/SimpleAudioPlayer/Plugin.SimpleAudioPlayer.iOS/SimpleAudioPlayerImplementation.cs in SetVolume() line 187

player.SetVolume((float)left, (float)right); is incorrect because it takes floats for volume, duration (unlike the Android version).

I think what we should be using is player.Volume and player.Pan. But Pan takes a float -0.1 <= x <= 1.0 so converting to left, right is not necessary.

Now, my dev problem here is that whenever I call our ISimpleAudioPlayer.Volume or ISimpleAudioPlayer.Balance, the audio shoots over to the far right channel. Debugging the iOS code is not working well, but I can see the Pan is getting set to 0.9999 --- somewhere??

----
**Bug #2**
/Xamarin-Plugins/SimpleAudioPlayer/SimpleAudioPlayer/Plugin.SimpleAudioPlayer.Android/SimpleAudioPlayerImplementation.cs in SetVolume() line 221

Setting the opposite side to "volume" is probably incorrect.

Let's say volume = 1 (max) and Balance is set to -0.8. This should put 80% of the sound output to left and 20% to right, but the way the code is written, 80% will go left and 100% will go right. This will result in basically no perceptible difference.

Now, my dev problem here is that when I updated the code to fix the problem I just outlined, I got no sound whatsoever out of the player.

----
I was hoping to be able to submit a pull request, but I had some issues I wasn't able to resolve. Still, I hope this information helps. Maybe I will be able to look at it some more later on.

References:

- https://developer.apple.com/documentation/avfoundation/avaudioplayer/
- https://developer.xamarin.com/api/member/Android.Media.MediaPlayer.SetVolume/p/System.Single/System.Single/

**Comment by robbpriestley** [comment]
**Update**

After further research and experimentation, I created Pull Request #41. There are comments in the Pull Request.

Basically, iOS was easy to fix as it provides a Pan property. Android required some math.

My comments in section "Bug #2" above are not 100% accurate. What I was imagining there was something called the "linear pan rule." In the end I chose the superior "constant power pan rule" to help keep the volume amplitude up.

I hope this helps.

**Comment by adrianstevens** [comment]
Thanks @robbpriestley - I've merged your PR - I'll try and get a new build out next week

Cheers!

Adrian

**Comment by PierreLucB** [comment]
Great Job I had the problem too, I'm glad to hear it's fixed ! Many thanks !

**Comment by adrianstevens** [comment]
Thanks again everyone - closing issue
