### ISSUE TITLE
Mismatch between processor architecture for x64 (AMD64)

### ISSUE THREAD

**Issue by zwilkin** [adrianstevens/Xamarin-Plugins#43]
When updating from **_1.1.0_** _to_ _**1.3.0**_, I am unable to compile my x64 UWP application.

Here is the error that is occurring...

`
1>------ Rebuild All started: Project: EISPocketProperty4.UWP, Configuration: Release x64 ------
`
`
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): error MSB3270: There was a mismatch between the processor architecture of the project being built "AMD64" and the processor architecture of the reference "C:\Users\zach\.nuget\packages\xam.plugin.simpleaudioplayer\1.3.0\lib\UAP10\Plugin.SimpleAudioPlayer.dll", "x86". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
`
`========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
`

**Comment by JTOne123** [comment]
I've got the same error. XBOX support needed.

**Comment by christoroth** [comment]
I have this issue too. release build x86/x64 on UWP gives mismatch compilation error.

**Comment by PetrVobornik** [comment]
I have this error to, when I try to create package for Microsoft Store (.appxupload)

There was a mismatch between the processor architecture of the project being built "AMD64" and the processor architecture of the reference "C:\Users\user\.nuget\packages\xam.plugin.simpleaudioplayer\1.3.0\lib\UAP10\Plugin.SimpleAudioPlayer.dll", "x86". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.	MyApp.UWP

**Comment by HerrRiebmann** [comment]
Me also!
Trying to create an UWP app in x86 or x64.
Seems like the Plugin.SimpleAudioPlayer.dll in "SimpleAudioPlayer\lib\UAP10\" is not compiled with AnyCPU property.

@christoroth attempt works. Or replacing the dll from another folder then "UAP10".

**Comment by dberroa** [comment]
Writing to say I also have this issue with 1.3.0.

**Comment by ronnieoverby** [comment]
Same here.

**Comment by adrianstevens** [comment]
Interesting ..... I'll look into this and try and fix it this week.

**Comment by adrianstevens** [comment]
Confirmed - I'll update release 1.3.1 this week. Thanks everyone any sorry for the wait.

**Comment by adrianstevens** [comment]
Thank you everyone! This has been fixed in 1.3.1 - closing issue
