### ISSUE TITLE
how to get chord sound efficiently?

### ISSUE THREAD

**Issue by delifare** [adrianstevens/Xamarin-Plugins#44]
I want to play musical chords consecutively. Chords have 4 notes.Eech notes have a wav files. 
But after 4 chords, sound can't be heard. OnPlaybackEnded event catchs  after all chords play. When players stop and dispose  manually, more than four chords can be played. 
But, chord sounds ara not heard good.
Code block is as like as below.
Please help for getting efficient chord sounds using this way.

 public static void Play(List<choirNote> noteList)
        {
            var playerList = new List<ISimpleAudioPlayer>();

            foreach (var note in noteList)
            {
                playerList.Add(GetPlayer(GetFileFullNameByNote(note)));
            }

            foreach (var player in playerList)
            {
                player.Play();
            }
        }
        
          private static ISimpleAudioPlayer GetPlayer(string fileName)
        {
            ISimpleAudioPlayer player;

            using (var asset = Android.App.Application.Context.Assets.Open(fileName, Access.Streaming))
            {
                var stream = new MemoryStream();
                asset.CopyTo(stream);
                stream.Flush();
                stream.Position = 0;

                player = CrossSimpleAudioPlayer.CreateSimpleAudioPlayer();

                player.Load(stream);

                player.PlaybackEnded += delegate
                {
                    player.Dispose();
                };
            }

            return player;
        }

        private static string GetFileFullNameByNote(choirNote note)
        {
            return "sounds/" + GetFileNameByNote(note) + ".wav";
        }

**Comment by adrianstevens** [comment]
This is a great question - SimpleAudioPlayer was designed for simple sound and music playback. For multiple sounds you'll likely want to use a more powerful audio engine that supports audio mixing and normalizing.

**Comment by adrianstevens** [comment]
closing issue
