### ISSUE TITLE
.net standard 2.0 support

### ISSUE THREAD

**Issue by vwilson317** [adrianstevens/Xamarin-Plugins#46]
Any future plans to support .net standard 2.0?

**Comment by WinBase** [comment]
yes, i wondered the same. i downloaded the project , updated the nugets to the latest versions and changed the target frameworks to netstandard 2.0, and get a compile error in CrossSimpleAudioPlayer.cs at line:

return new SimpleAudioPlayerImplementation();

The type or namespace name 'SimpleAudioPlayerImplementation' could not be found (are you missing a using directive or an assembly reference?)

im a newbie at cross platform and xamarin so not sure how to change it, so please advise

**Comment by adrianstevens** [comment]
I just tested this yesterday and it is working on .NET Standard 2.0.

You can see an example here: https://github.com/adrianstevens/Xamarin-Forms/tree/master/Radio and the current sample is using a .NET Standard 2.0 library https://github.com/adrianstevens/Xamarin-Plugins/tree/master/SimpleAudioPlayer/Samples

Take a look at the example above and feel free to reopen this issue if you still can't get it working.

Cheers!

I'll
