### ISSUE TITLE
[iOS] iOS crashes on the play and the prepare method when simultaneous sounds are playing

### ISSUE THREAD

**Issue by JTOne123** [adrianstevens/Xamarin-Plugins#47]
I got several crashes after my try to start and play a few sounds at the same time.

It works well on Android and UWP, but not on iOS.

I cannot catch the exception, because they happen somewhere in a kernel. 

_Here are crash logs_

**prepare**
![image](https://user-images.githubusercontent.com/3457140/53081084-c30b1180-3502-11e9-90f1-7176fa256ce7.png)

**play**
![image](https://user-images.githubusercontent.com/3457140/53081136-e59d2a80-3502-11e9-8da1-41abdf4817af.png)

I play my sound in this way

`
if (audioPlayer.Load(ResourceLoader.GetEmbeddedResourceStream(ResourceLoader.Assembly, fileName)))
 {
      audioPlayer.Play();
 }
`

What I'm doing wrong? How correct way to play sounds in parallel?

**Comment by adrianstevens** [comment]
You'll need a separate instance of SimpleAudioPlayer for each sound - are you using multiple or sharing a single instance?

**Comment by JTOne123** [comment]
yep, I did it in this way
Thank you for answer
