### ISSUE TITLE
Android Issue - Stop before Start

### ISSUE THREAD

**Issue by terinfire** [adrianstevens/Xamarin-Plugins#51]
I discovered this issue when trying to make an application that potentially loops different musics/sounds.  The first order of business is to always "Stop" all sounds from playing, which resulted in a strange error (-38, 0).  This prevents the sounds from EVER playing and puts the MediaPlayer in a "bad" state.

The implementation as it is, is a little fragile (but I have a pretty simple fix):

In Plugin.SimpleAudioPlayer.Android/SimpleAudioPlayerImplementation.cs

Line 195 -- Add:
if(!IsPlaying) return;

Basically what happens is that if you try to Stop() something that hasn't ever been Start()'d, it tries to do a SeekTo() which fails.  It appears SeekTo fails when trying to set to the same value, somehow.

You may consider also adding these checks to your Seek() method and then calling that instead of on the player member variable directly.  Further, you may also check if CanSeek on the Property itself.

Appreciate ALL of the groundwork you did -- was frustrating trying to figure out what was going on, but now that I've found it, I've realized the library is a little fragile.

**Comment by adrianstevens** [comment]
Thank you again @terinfire for the feedback and the pull request! It's very appreciated.

It's been merged and published - closing this issue.
