### ISSUE TITLE
[UWP] Doesn't properly load MemoryStream

### ISSUE THREAD

**Issue by rpreams** [adrianstevens/Xamarin-Plugins#53]
I appear to be having an issue reading a memory stream in UWP.  Currently, in Android and iOS, I am successfully able to convert a wav file from a Base 64 string to a memory stream, and queue it up and play.  On UWP, it fails to load in and read the duration to set some values in my app.  Tried both 1.3.0 and 1.1.0 but both appear to be not working.  Has anyone else experienced this issue?

Here is a snippet of my ViewModel loading and setting up the player

 vmplayer = CrossSimpleAudioPlayer.Current;
            vmplayer.PlaybackEnded += PlaybackEnded;
            MemoryStream = new MemoryStream(Convert.FromBase64String(voicemail));
            CurrentPosition = TimeSpan.FromSeconds(Math.Round(vmplayer.CurrentPosition)).ToString("mm\\:ss");
            vmplayer.Load(MemoryStream);

Failure occurs when setting my slider max value to be equal to vmplayer.duration after above has been executed.

trackSlider.Maximum = Math.Round(vm.vmplayer.Duration);

**Comment by adrianstevens** [comment]
Interesting - I'd try embedding the wave file directly in a sample app (without base 64 encoding) and see if it works. If it does, try embedding the base64 encoding version, decode and play.

A couple of things come to mind:
It could be an incompatible wave file that works / is supported on the other platforms 
Or possibility there's some unneeded header info in your base 64 string 

Good luck!

**Comment by rpreams** [comment]
After some further testing and code revisions, what I found is that there is a bit of delay from loading a stream with UWP vs Android and iOS.  What i ended up doing is adding a 1 second delay before evaluating the data behind the CrossSimpleAudioPlayer.Current.  I don't know if that helps with debugging or troubleshooting, but this does appear to resolve the issue I was experiencing.

**Comment by adrianstevens** [comment]
excellent - closing issue
