### ISSUE TITLE
Random volume level changes when playing sound repeatedly

### ISSUE THREAD

**Issue by voxoid0** [adrianstevens/Xamarin-Plugins#55]
on UWP platform (haven't tried this code yet on iOS nor Android), I'm playing the same sound repeatedly about every 1s, but sometimes it is full volume and sometimes it is half volume. About 50/50, but the switch is pseudorandom. 

```
            _audioPlayer = CrossSimpleAudioPlayer.CreateSimpleAudioPlayer();
            _audioPlayer.Load("metronome-2s.wav");
            _metronomeTimer = new Timer(state =>
            {
                //_audioPlayer.Volume = 1.0;
                //_audioPlayer.Stop();
                _audioPlayer.Play();
                Trace.TraceInformation("TICK!!! " + Guid.NewGuid());
            }, null, Timeout.Infinite, Timeout.Infinite);

    ...

                _metronomeTimer.Change(TimeSpan.Zero, TimeSpan.FromMinutes(1.0 / _metronomeBpm));

```

My particular sound sample is 2s long. I notice that if I leave enough time in between Play() calls for the entire sound to play, the volume change does not occur. So my guess is that when I call Play() while it is still playing, then somehow the next time it plays it plays twice on top of each other and thereby it is twice as loud. However I also tried calling Stop() each time before calling Play() (see commented line), but I still experience the same problem.

I've attached the sound clip.
[metronome-2s.zip](https://github.com/adrianstevens/Xamarin-Plugins/files/3336377/metronome-2s.zip)

**Comment by adrianstevens** [comment]
I'll step back and talk about another potential problem. I suspect this plugin won't give you enough accuracy for a metronome. I've found the humans are really good at detecting slight timing issues.

You'll likely need to use a lower-level API and use a continuous audio stream. 

All that being said, we shouldn't see the behavior you're seeing. I'll try and do some testing over the next couple of weeks and see if I can reproduce the issue.

**Comment by voxoid0** [comment]
Thanks, Adrian. The double volume problem does not occur on iOS. Though I did notice the inconsistent delay when a sounds is played, making the metronome...not so metronomic; good observation.
