### ISSUE TITLE
Enhancement Audio through Speaker, ear peace or Bluetooth

### ISSUE THREAD

**Issue by magtimmermans** [adrianstevens/Xamarin-Plugins#57]
Hi,

Would it be possible to add an option that the audio will be played by Speaker or ear-peace or Bluetooth (A2DP)?

**Comment by adrianstevens** [comment]
This isn't consistent across every supported platform so I think this better handled outside of the plugin (i.e. directly in your application code).

**Comment by adrianstevens** [comment]
closing issue

**Comment by michaelonz** [comment]
Hi - Does anyone have any sample code where there app is using SimpleAudioPlayer to play sound through the speaker (not the earpiece) on IOS (Seems fine on android)..... I have tried so much sample code but nothing works more than once - I am wondering if anyone has actually got this to work?
