### ISSUE TITLE
Desync after seeking two players that were previously synced

### ISSUE THREAD

**Issue by TheCaveOfWonders** [adrianstevens/Xamarin-Plugins#62]
In UWP, I have two audio players that begin synced together. Everything works fine if i don't seek, they stay synced all the way. When i do a seek, often they desync by a little bit (in the milliseconds, but enough to be noticeable).

I tried a lot of different ways to do the seek and try and fix the desync, but nothing worked.
Currently the way I'm doing the seek is: Pause => Seek => Play. I tried just seek, i tried adding delays between the seek and the play, tried running the entire thing on its own thread, tried a "forced resync" 1000ms after the seek is done (basically seek one player to the time of the other player), tried a combination of all that.

Nothing worked.

What is even more weird is the position delta for the players does not seem to go with what is actually heard, like sometimes it would say the difference is 0 ms, yet you can clearly hear a desync, and other times it would say the difference is 5 ms yet there is no desync. To get the delta i have a thread running in the background, and it just outputs Math.Abs(player1.CurrentPosition - player2.CurrentPosition)*1000.

I understand this is meant as a simple audio player, I just figured i would be able to play 2 of them in sync. If that's beyond this player's capabilities please let me know.

Thanks for your understanding.

**Comment by adrianstevens** [comment]
This is more likely a limitation of the underlying UWP MediaPlayer class. This isn't a use-case the plugin but if you see any opportunity for improvement please submit a pull request.

Thanks!
