### ISSUE TITLE
Null Reference Exception on Android. iOS untested.

### ISSUE THREAD

**Issue by Jakar510** [adrianstevens/Xamarin-Plugins#69]
Android Exception. iOS untested.	

> System.NullReferenceException: Object reference not set to an instance of an object.
>   at Plugin.SimpleAudioPlayer.SimpleAudioPlayerImplementation.Load (System.IO.Stream audioStream) [0x00000] 
> 			in F:\dev\open\Xamarin-Plugins\SimpleAudioPlayer\SimpleAudioPlayer\Plugin.SimpleAudioPlayer.Android\SimpleAudioPlayerImplementation.cs:93

**Comment by adrianstevens** [comment]
Hi @Jakar510  - can you provide more details? Where is the audio file located and how are you loading it?

**Comment by adrianstevens** [comment]
closing issue
