### ISSUE TITLE
Samsung TV

### ISSUE THREAD

**Issue by swift11** [adrianstevens/Xamarin-Plugins#7]
Hello,

Could you add support for Samsung TV please
https://developer.tizen.org/development/guides/.net-application

**Comment by adrianstevens** [comment]
@swift11 absolutely - it's on my ToDo list :)

I'm hoping to have it done before the end of the year.

**Comment by adrianstevens** [comment]
I'll be reviewing this pull request this week:
https://github.com/adrianstevens/Xamarin-Plugins/pull/14

 As long as testing goes well I'll have a beta version out soon.

**Comment by drznathou** [comment]
So how is it going with Tizen?

**Comment by adrianstevens** [comment]
the Tizen package has been published - would love to hear feedback

**Comment by Azmarel** [comment]
Hello, On Tizen the method CrossSimpleAudioPlayer.CreateSimpleAudioPlayer() returns null.
