### ISSUE TITLE
No Playback Ended callback if Siri is activated

### ISSUE THREAD

**Issue by chrisfoulds** [adrianstevens/Xamarin-Plugins#74]
If you activate Siri when an audio message is playing PlaybackEnded is never called.

**Comment by chrisfoulds** [comment]
https://developer.apple.com/documentation/avfoundation/avaudioplayerdelegate/1389160-audioplayerdidfinishplaying
Audio is interrupted but no callback to inform the main app is available.

**Comment by adrianstevens** [comment]
since this is expected behavior I'm closing the issue
