### ISSUE TITLE
[Question] Getting file stream from url

### ISSUE THREAD

**Issue by Saxby-source** [adrianstevens/Xamarin-Plugins#76]
Hey, first off I love this plugin it's saved my life on the project I'm working on cheers :P.

but I've quickly realized I need a lot of audio files within my app, so I am trying to go down the route of storing the files on the cloud (haven't decided the best option for hosting yet), and I was wondering if it is possible to load the file stream through a URL and play the audio file, or do I need to be looking at a different type of implementation/plugin?

**Comment by adrianstevens** [comment]
This should work - the easiest strategy would be to download the file to the device and then open the file locally.
