### ISSUE TITLE
Stops playing when pressing home button on iOS

### ISSUE THREAD

**Issue by DavidBemerguy** [adrianstevens/Xamarin-Plugins#8]
Thanks for the great tool.
I am using an iPhone 6 iOS 11 and music is playing good, but when I press home button the app stops playing, resuming if I put the app on foreground.
I also Enabled background audio in the info.plist.

Thanks

**Comment by adrianstevens** [comment]
@DavidBemerguy yes it's currently only able to play audio while the app is in the foreground. I should be able to add this in to the next update.

Cheers!

**Comment by DavidBemerguy** [comment]
In fact I found out that loading audio session on application did finish
enabled background play

**Comment by adrianstevens** [comment]
great! closing issue

**Comment by traceyhemp12** [comment]
@DavidBemerguy, can you explain what you did to fix your issue? I am having a similar issue.
