### ISSUE TITLE
Need to add support for playing from http without converting to stream.

### ISSUE THREAD

**Issue by Jack-Paul** [adrianstevens/Xamarin-Plugins#82]
Hi,

I need to stream audio using an HTTP link, in my case many links are huge in size, so when I convert from URL to stream, it's taking a long time before start to playing, kindly suggest a solution or workaround for this case.

Thanks.

**Comment by UniponKelvyn** [comment]
Hello, how are you?

Did you find any way to solve it? I have the same problem.

**Comment by adrianstevens** [comment]
Duplicate of issue #3  - please join the conversation there :)
